news_agency_app/urls.py
from . import views
from django.urls import path

from news_agency_app.views import TopicCreateView, TopicUpdateView


urlpatterns = [
    path("", views.index, name="index"),
    path("newspapers/", views.NewspaperListView.as_view(), name="newspaper-list"),
    path(
        "newspapers/<int:pk>/",
        views.NewspaperDetailView.as_view(),
        name="newspaper-detail",
    ),
    path(
        "newspapers/create/",
        views.NewspaperCreateView.as_view(),
        name="newspaper-create",
    ),
    path(
        "newspapers/<int:pk>/update/",
        views.NewspaperUpdateView.as_view(),
        name="newspaper-update",
    ),
    path(
        "newspapers/<int:pk>/delete/",
        views.NewspaperDeleteView.as_view(),
        name="newspaper-delete",
    ),
    path("topics/", views.TopicListView.as_view(), name="topic-list"),
    path("topics/<int:pk>/", views.TopicDetailView.as_view(), name="topic-detail"),
    path("topics/create/", TopicCreateView.as_view(), name="topic-create"),
    path("topics/<int:pk>/update/", TopicUpdateView.as_view(), name="topic-update"),
    path("redactors/", views.RedactorListView.as_view(), name="redactor-list"),
    path(
        "redactors/<int:pk>/",
        views.RedactorDetailView.as_view(),
        name="redactor-detail",
    ),
    path("login/", views.CustomLoginView.as_view(), name="login"),
    path("logout/", views.CustomLogoutView.as_view(), name="logout"),
]

app_name = "news_agency_app"

newspaper_agency/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("news_agency_app.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [
        path("__debug__/", include(debug_toolbar.urls)),
    ] + urlpatterns

news_agency_app/models.py
from django.contrib.auth.models import Group, Permission
from django.db import models
from django.contrib.auth.models import AbstractUser


class Topic(models.Model):
    name = models.CharField(max_length=255, unique=True)

    def __str__(self):
        return self.name


class Redactor(AbstractUser):
    years_of_experience = models.PositiveIntegerField(default=0)

    groups = models.ManyToManyField(Group, related_name="redactors", blank=True)

    user_permissions = models.ManyToManyField(
        Permission, related_name="redactors_permissions", blank=True
    )

    def __str__(self):
        return self.username


class Newspaper(models.Model):
    title = models.CharField(max_length=255)
    content = models.TextField()
    published_date = models.DateTimeField()
    topic = models.ForeignKey(
        Topic, on_delete=models.CASCADE, related_name="newspapers"
    )
    publishers = models.ManyToManyField(Redactor, related_name="newspapers")

    def __str__(self):
        return self.title

news_agency_app/forms.py
from django import forms

from news_agency_app.models import Newspaper, Redactor, Topic


class NewspaperForm(forms.ModelForm):
    publishers = forms.ModelMultipleChoiceField(
        queryset=Redactor.objects.all(),
        widget=forms.CheckboxSelectMultiple,
        required=False,
    )

    class Meta:
        model = Newspaper
        fields = ["title", "content", "published_date", "topic", "publishers"]


class RedactorExperienceUpdateForm(forms.ModelForm):
    years_of_experience = forms.IntegerField(min_value=0)

    class Meta:
        model = Redactor
        fields = ["years_of_experience"]


class TopicForm(forms.ModelForm):
    class Meta:
        model = Topic
        fields = ["name"]

news_agency_app/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import LoginView, LogoutView

from django.db.models import Q
from django.shortcuts import render
from django.urls import reverse_lazy

from django.views import generic
from django.views.generic import (
    ListView,
    DetailView,
    CreateView,
    UpdateView,
    DeleteView,
)

from news_agency_app.models import Topic, Newspaper, Redactor


def index(request):
    """View function for the home page of the site with visit count."""

    request.session["num_visits"] = request.session.get("num_visits", 0) + 1
    num_newspapers = Newspaper.objects.count()
    num_topics = Topic.objects.count()
    num_redactors = Redactor.objects.count()

    context = {
        "num_newspapers": num_newspapers,
        "num_topics": num_topics,
        "num_redactors": num_redactors,
        "num_visits": request.session["num_visits"],
    }

    return render(request, "news_agency/index.html", context=context)


class TopicListView(ListView):
    model = Topic
    template_name = "news_agency/topic_list.html"
    context_object_name = "topics"


class TopicDetailView(DetailView):
    model = Topic
    template_name = "news_agency/topic_detail.html"


class TopicCreateView(CreateView):
    model = Topic
    fields = ["name"]
    template_name = "news_agency/topic_form.html"
    success_url = reverse_lazy("news_agency:topic_list")


class TopicUpdateView(UpdateView):
    model = Topic
    template_name = "news_agency/topic_form.html"
    fields = ["name"]
    success_url = reverse_lazy("news_agency:topic-list")


class NewspaperListView(ListView):
    model = Newspaper
    template_name = "news_agency/newspaper_list.html"
    context_object_name = "newspapers"


class NewspaperDetailView(DetailView):
    model = Newspaper
    template_name = "news_agency/newspaper_detail.html"


class NewspaperCreateView(CreateView):
    model = Newspaper
    fields = ["title", "content", "published_date", "topic", "publishers"]
    template_name = "news_agency/newspaper_form.html"
    success_url = reverse_lazy("newspaper-list")


class NewspaperUpdateView(UpdateView):
    model = Newspaper
    fields = ["title", "content", "published_date", "topic", "publishers"]
    template_name = "news_agency/newspaper_form.html"
    success_url = reverse_lazy("newspaper-list")


class NewspaperDeleteView(DeleteView):
    model = Newspaper
    template_name = "news_agency/newspaper_confirm_delete.html"
    success_url = reverse_lazy("newspaper-list")


class RedactorListView(ListView):
    model = Redactor
    template_name = "news_agency/redactor_list.html"
    context_object_name = "redactors"


class RedactorDetailView(DetailView):
    model = Redactor
    template_name = "news_agency/redactor_detail.html"


class CustomLoginView(LoginView):
    template_name = "registration/login.html"


class CustomLogoutView(LogoutView):
    template_name = "registration/logged_out.html"


class SearchListView(generic.ListView):
    search_fields = []

    def get_queryset(self):
        queryset = super().get_queryset()
        search = self.request.GET.get("search")

        if search:
            q_objects = Q()
            for field in self.search_fields:
                q_objects |= Q(**{f"{field}__contains": search})
            queryset = queryset.filter(q_objects)

        return queryset

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  {% block title %}
    <title>Newspaper</title>
  {% endblock %}
  <link rel="stylesheet"
        href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
        integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2"
        crossorigin="anonymous">
  {% load static %}
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">

</head>

<body class="d-flex flex-column min-vh-100">

{% include "includes/navbar.html" %}

<div class="container-fluid flex-grow-1">
  <div class="row">
    <div class="col-sm-2 pt-3">
      {% block sidebar %}
        {% include "includes/sidebar.html" %}
      {% endblock %}
    </div>

    <div class="col-sm-10 pt-3">
      {% block content %}{% endblock %}
      {% block pagination %}
        {% include "includes/pagination.html" %}
      {% endblock %}

    </div>
  </div>
</div>

{% block footer %}
  {% include "includes/footer.html" %}
{% endblock %}

<script src="https://code.jquery.com/jquery-3.5.1.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ho+j7jyWK8fNQe+A12X63V/UBr5p1hb7xXzOU3P5B5F6K5l5xTmtU5YRsqeFOeBgp"
        crossorigin="anonymous"></script>

</body>

</html>

templates/form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <div class="container mt-5">
    <div class="row justify-content-center">
      <div class="col-md-6">
        <div class="card shadow-lg p-4">
          <h2 class="text-center">{{ title }}</h2>

          <form method="post" class="mt-3">
            {% csrf_token %}
            {{ form|crispy }}

            <div class="d-flex justify-content-between mt-3">
              <button type="submit" class="btn btn-success btn-lg">Submit</button>
              <a href="{% url 'news_agency_app:index' %}" class="btn btn-secondary btn-lg">Cancel</a>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

templates/includes/footer.html
<footer class="footer mt-auto py-3 bg-light">
  <div class="container text-center">
    <span class="text-muted">© {% now "Y" %} News Agency. All rights reserved.</span>
  </div>
</footer>

templates/includes/navbar.html
<nav class="navbar navbar-dark bg-dark">
  <ul class="navbar-nav flex-row">
    <li class="nav-item mx-3">
      <a class="nav-link text-light" href="{% url 'news_agency_app:index' %}">Home</a>
    </li>
  </ul>

  <ul class="navbar-nav flex-row">
    {% if user.is_authenticated %}
      <li class="nav-item mx-3">
        <span class="navbar-text text-light">Welcome, {{ user.username }}</span>
      </li>
      <li class="nav-item mx-3">
        <a class="nav-link text-light" href="{% url 'logout' %}">Logout</a>
      </li>
    {% else %}
      <li class="nav-item mx-3">
        <a class="nav-link text-light" href="{% url 'login' %}">Login</a>
      </li>
    {% endif %}
  </ul>
</nav>

templates/includes/pagination.html
{% if is_paginated %}
  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li class="page-item">
        <a href="?page= {{ page_obj.previous_page_number }}" class="page-link">prev</a>
      </li>
    {% endif %}
    <li class="page-item active">
      <span class="page-link">{{ page_obj.number }} of {{ paginator.num_pages }}</span>
    </li>
    {% if page_obj.has_next %}
      <li class="page-item">
        <a href="?page= {{ page_obj.next_page_number }}" class="page-link">next</a>
      </li>
    {% endif %}
  </ul>
{% endif %}

templates/includes/sidebar.html
<div class="sidebar-wrapper">
  <ul class="sidebar-nav list-group">
    <li class="list-group-item">
      <a href="{% url 'news_agency_app:topic-list' %}">Topics</a>
    </li>
    <li class="list-group-item">
      <a href="{% url 'news_agency_app:newspaper-list' %}">Newspapers</a>
    </li>
    <li class="list-group-item">
      <a href="{% url 'news_agency_app:redactor-list' %}">Publishers</a>
    </li>
  </ul>
</div>

templates/news_agency/index.html
{% extends "base.html" %}

{% block content %}

  <h1>News Agency Home</h1>
  <p>Welcome to our news platform!</p>

  <h2>Statistics</h2>
  <p>Our agency currently has:</p>
  <ul>
    <li><strong>Newspapers:</strong> {{ num_newspapers }}</li>
    <li><strong>Topics:</strong> {{ num_topics }}</li>
    <li><strong>Redactors:</strong> {{ num_redactors }}</li>
  </ul>

  <p>You have visited this page
    {{ num_visits }} time{{ num_visits|pluralize }}.
  </p>

{% endblock %}

templates/news_agency/newspaper_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Confirm Deletion</h1>
  <p>Are you sure you want to delete "{{ newspaper.title }}"?</p>

  <form method="post">
    {% csrf_token %}
    <button type="submit" class="btn btn-danger">Yes, delete</button>
    <a href="{% url 'news_agency_app:newspaper-list' %}" class="btn btn-secondary">Cancel</a>
  </form>
{% endblock %}

templates/news_agency/newspaper_detail.html
{% extends "base.html" %}

{% block content %}
  <h1>{{ newspaper.title }}</h1>
  <p><strong>Published on:</strong> {{ newspaper.published_date }}</p>
  <p><strong>Topic:</strong> {{ newspaper.topic.name }}</p>
  <p>{{ newspaper.content }}</p>

  <h3>Publishers:</h3>
  <ul>
    {% for publisher in newspaper.publishers.all %}
      <li>{{ publisher.username }}</li>
    {% endfor %}
  </ul>

  <a href="{% url 'news_agency_app:newspaper-update' pk=newspaper.id %}" class="btn btn-warning">Edit</a>
  <a href="{% url 'news_agency_app:newspaper-delete' pk=newspaper.id %}" class="btn btn-danger">Delete</a>
{% endblock %}

templates/news_agency/newspaper_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h2>{{ title }}</h2>

  <form method="post">
    {% csrf_token %}
    {{ form|crispy }}

    <button type="submit" class="btn btn-primary">Submit</button>
    <a href="{% url 'news_agency_app:newspaper-list' %}" class="btn btn-secondary">Cancel</a>
  </form>
{% endblock %}

templates/news_agency/newspaper_list.html
{% extends "base.html" %}

{% block content %}
  <h1>
    Newspaper list
  </h1>
  {% if newspapers %}
    <ul>
      {% for newspaper in newspapers %}
        <li>
          <a href="{% url 'news_agency_app:newspaper-detail' pk=newspaper.id %}">{{ newspaper.title }}</a>
          ({{ newspaper.published_date }})
        </li>
      {% endfor %}
    </ul>
  {% else %}
    <p>No newspapers available.</p>
  {% endif %}
  {% if user.is_authenticated %}
    <a href="{% url 'news_agency_app:newspaper-create' %}" class="btn btn-primary link-to-page">
      Create
    </a>
  {% endif %}
{% endblock %}

templates/news_agency/redactor_detail.html
{% extends "base.html" %}

{% block content %}
  <h1>{{ redactor.username }}</h1>
  <p><strong>Email:</strong> {{ redactor.email }}</p>
  <p><strong>Years of Experience:</strong> {{ redactor.years_of_experience }}</p>

  <h3>Published Newspapers:</h3>
  <ul>
    {% for newspaper in redactor.newspapers.all %}
      <li><a href="{% url 'news_agency_app:newspaper-detail' pk=newspaper.id %}">{{ newspaper.title }}</a></li>
    {% endfor %}
  </ul>
{% endblock %}

templates/news_agency/redactor_list.html
{% extends "base.html" %}

{% block content %}
  <h1>Redactors</h1>
  {% if redactors %}
    <ul>
      {% for redactor in redactors %}
        <li>
          <a href="{% url 'news_agency_app:redactor-detail' pk=redactor.id %}">{{ redactor.username }}</a>
          ({{ redactor.years_of_experience }} years of experience)
        </li>
      {% endfor %}
    </ul>
  {% else %}
    <p>No redactors found.</p>
  {% endif %}
{% endblock %}

templates/news_agency/topic_detail.html
{% extends "base.html" %}

{% block content %}
  <h1>{{ topic.name }}</h1>
  <p><strong>Newspapers in this topic:</strong></p>
  <ul>
    {% for newspaper in topic.newspapers.all %}
      <li><a href="{% url 'news_agency_app:newspaper-detail' pk=newspaper.id %}">{{ newspaper.title }}</a></li>
    {% endfor %}
  </ul>

  <a href="{% url 'news_agency_app:topic-list' %}" class="btn btn-secondary">Back to list</a>
{% endblock %}

templates/news_agency/topic_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h2>{{ title }}</h2>

  <form method="post">
    {% csrf_token %}
    {{ form|crispy }}

    <button type="submit" class="btn btn-primary">Submit</button>
    <a href="{% url 'news_agency_app:topic-list' %}" class="btn btn-secondary">Cancel</a>
  </form>
{% endblock %}

templates/news_agency/topic_list.html
{% extends "base.html" %}

{% block content %}
  <h1>
    Topic list
  </h1>
  {% if topics %}
    <ul>
      {% for topic in topics %}
        <li>
          <a href="{% url 'news_agency_app:topic-detail' pk=topic.id %}">{{ topic.name }}</a>
        </li>
      {% endfor %}
    </ul>
  {% else %}
    <p>No topics available.</p>
  {% endif %}
  {% if user.is_authenticated %}
    <a href="{% url 'news_agency_app:topic-create' %}" class="btn btn-primary link-to-page">
      Create
    </a>
  {% endif %}
{% endblock %}